
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
      <http://lblod.data.gift/concept-schemes/627415c1-d378-4fcc-859f-a6c99d9b1326> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
      <http://www.w3.org/2004/02/skos/core#prefLabel>"Current work status";
      <http://mu.semte.ch/vocabularies/core/uuid> "627415c1-d378-4fcc-859f-a6c99d9b1326".

    <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Werknemer> a <http://www.w3.org/2004/02/skos/core#Concept>;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/627415c1-d378-4fcc-859f-a6c99d9b1326>;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Werknemer";
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/Doelgroep>;
      <http://mu.semte.ch/vocabularies/core/uuid> "3b32c3f3-e908-4291-b0b4-9e46ed4251a5".

    <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Zelfstandig> a <http://www.w3.org/2004/02/skos/core#Concept>;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/627415c1-d378-4fcc-859f-a6c99d9b1326>;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Zelfstandig";
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/Doelgroep>;
      <http://mu.semte.ch/vocabularies/core/uuid> "f8700f53-65fa-4a82-9df5-4284328008f0".

    <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Werkzoekend> a <http://www.w3.org/2004/02/skos/core#Concept>;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/627415c1-d378-4fcc-859f-a6c99d9b1326>;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Werkzoekend";
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/Doelgroep>;
      <http://mu.semte.ch/vocabularies/core/uuid> "4f7831c8-c749-4598-81eb-9033fec5b062".

    <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/(Deels)Arbeidsongeschikt> a <http://www.w3.org/2004/02/skos/core#Concept>;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/627415c1-d378-4fcc-859f-a6c99d9b1326>;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "(Deels) arbeidsongeschikt";
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/Doelgroep>;
      <http://mu.semte.ch/vocabularies/core/uuid> "b20e3186-3dfd-4503-aa63-1004a396bb0f".

    <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/AndereWerksituatie> a <http://www.w3.org/2004/02/skos/core#Concept>;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/627415c1-d378-4fcc-859f-a6c99d9b1326>;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Andere werksituatie";
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/Doelgroep>;
      <http://mu.semte.ch/vocabularies/core/uuid> "3f1b8f7b-2160-4b61-acb8-cccee5db81a3".
    }
}